language: java
jdk:
  - oraclejdk8

sudo: required

services:
  - docker

after_success:
  - docker build -t xxcxy/killer-backend .
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push xxcxy/killer-backend
